spring:
  application:
    name: prod-default
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:9093/eureka
  instance:
    prefer-ip-address: true
